#pragma once
const int SIZE = 8;//define the size of array which generated by random()
//获取数组的最大子序列和
int getMaxSumSubSequence(int* nums);
//获取数组的最小子序列和
int getMinSumSubSequence(int* nums);
//获取数组的最小正子序列和
int getPositiveMinSumSubSequence(int *nums);
//获取数组的最小正子序列和
int getPositiveMinSumSubSequence2(int* nums);
//获取数组的最大乘积
int getMaxMultiSubSequence(int *nums);
